### ISSUE TITLE
検索画面の実装

### ISSUE THREAD

**Issue by yukkxi** [NKotani/AE2Team2#5]

**Comment by yukkxi** [comment]
9/5中に完成予定

**Comment by mirroris** [comment]
検索画面は大体できた。コンポーネントが重なる理由があまりわかっていないので、順序を工夫したい。
ボタン動作の関数を明日に実装。
次の課題
- レイアウトずれ
- ボタン押下時の動作未定義
- Componentと分けていない

<img width="792" alt="image" src="https://github.com/NKotani/AE2Team2/assets/84974879/e27292ed-a57d-462c-a4c9-96c481a028d3">


https://qiita.com/s_yasunaga/items/05e56fad4631f7bc7fe9

**Comment by mirroris** [comment]
[概要]
JSONをまとめて送信できるまでソースコードをとりあえずcommitした。
Docker環境がないため、エンドポイントの設定はまだ。

[詳細]


[バグ]
- sendData()内部のエンドポイント先を'endpoint'とだけしているのでまだ送信できていない。
- ここを治してくれると助かる。

- ローカルのを単純に写しただけなので、component/ -> views/　に変える必要があるところが多々あるかも

**Comment by mirroris** [comment]
[概要]
後はルータの設定だけ
環境がないので後はお願いしたい

[詳細]
残りの作業は<script>内がほとんど
- responseのデータをルータのパラメタとして保存してpropsでSearcher.vueに取り込む
- postするときのendpointの設定

[Append]
- sendData内でPOSTしているのでそこ参照するのがよい

**Comment by mirroris** [comment]
現在は条件の追加と削除も可能になっていて、
余っている食材のボタンの位置と色は修正が必要かもしれないです
<img width="764" alt="image" src="https://github.com/NKotani/AE2Team2/assets/84974879/1cb966f2-1fd3-47bc-ac2e-0c2bc7c68f16">

**Comment by melon0658** [comment]
検索画面から検索結果画面へのルーティング設定完了
